FS-001: added factory task stack and queue pages
katebelchynska/machine-factory pull request #1
Opened 2023-06-01 15:25 UTC by katebelchynska

2023-06-01 16:36 UTC, NickForge requested changes

2023-06-01 16:36 UTC, NickForge commented on src/hooks/hooks.ts
> +import { TypedUseSelectorHook, useDispatch, useSelector } from 'react-redux';
it probably should contains under store directory

2023-06-01 16:36 UTC, NickForge commented on src/main.tsx
> +    path: "/",
Please add constants for paths

2023-06-01 16:36 UTC, NickForge commented on src/main.tsx
> +const router = createBrowserRouter([
Nice. You can transfer it in separate file

2023-06-01 16:36 UTC, NickForge commented on src/pages/404.tsx
> +// import { Link } from "react-router-dom";
please remove comment

2023-06-01 16:36 UTC, NickForge commented on src/pages/404.tsx
> +    <Box
You can simplify

```
const Page404 = () => (
  <Box
```

2023-06-01 16:36 UTC, NickForge commented on src/pages/MachineActionsPage.tsx
> +      console.log("component unmounting...");
Do you need this console?

2023-06-01 16:36 UTC, NickForge commented on src/pages/MachineActionsPage.tsx
> +  function addMachineAction() {
in component better use arrow function.

2023-06-01 16:36 UTC, NickForge commented on src/pages/MachineActionsPage.tsx
> +              return <ListItem key={item.actionId}>{item.title}</ListItem>;
I'm not sure that actionId will be unique all time.

2023-06-01 16:38 UTC, NickForge commented
Please check and fix similar comments in other components =)

2023-06-02 09:46 UTC, NickForge requested changes

2023-06-02 09:46 UTC, NickForge commented on src/constants/routes.ts
> +    path: "/",
and paths as separate constants, because you will use this paths not only in this file

2023-06-02 09:46 UTC, NickForge commented on src/pages/404.tsx
> +        <Link href="/" underline="hover">
please use constant with path instead string.
It's exactly what i've talked about =)

2023-06-02 09:46 UTC, NickForge commented on src/pages/MachineEventsPage.tsx
> +              return (
you can simplify =)
`list.map((item) => (`

2023-06-02 09:46 UTC, NickForge commented on src/slices/machineActions/machineActionsSlice.ts
> +const initialState: Array<Action> = [
more readable `Action[]`

2023-06-02 09:46 UTC, NickForge commented on src/slices/machineEvents/machineEventsSlice.ts
> +const initialState: Array<Event> = [
same

2023-06-02 09:47 UTC, NickForge commented
Please add 👍 to each fixed comment

2023-06-02 10:31 UTC, NickForge requested changes

2023-06-02 10:31 UTC, NickForge commented on src/constants/routes.ts
> +export const PAGE_404 = "*";
there were all ok =)

Please create `constants/navigation.ts` instead and add there
```
export const PATH = {
  MAIN_PAGE: "/",
  EVENTS_PAGE: "/events",
  PAGE_404: "*",
}

export const router = ....
``

2023-06-02 10:31 UTC, NickForge commented on src/pages/App.tsx
> +const router = createBrowserRouter([
please transfer it to `constants/navigation.ts`

2023-06-02 11:14 UTC, NickForge approved these changes

2023-06-02 11:58 UTC, stanislavSoro approved these changes
Lgtm!

2023-06-02 12:04 UTC, merged